## Step by step api's methods description

In [2]:
import os
import re
import pandas as pd
import numpy as np
import qiime2
from qiime2 import Artifact
from qiime2.plugins import metadata, feature_table, diversity, emperor
from q2_emperor import plot, procrustes_plot, biplot, generic_plot
from scipy.spatial.distance import squareform, pdist
import skbio

In [3]:
!ls ..

Dockerfile  README.md	    api			notebooks
Makefile    Untitled.ipynb  docker-compose.yml	run_server.sh

In [4]:
!pwd

/ClusterApp/notebooks

In [5]:
# Change directory to import function from api
os.chdir('..')

In [6]:
os.getcwd()

'/ClusterApp'

In [7]:
os.listdir('api/src/service/factorys')

['__init__.py', 'normalization', 'ScalingFactory.py', '__pycache__']

In [8]:
#from api.utils import qiime2PCoA
from api.src.service.gnps import Proteosafe

In [9]:
taskid = 'a0b4377f6e4540268602c30fedf69b0b'
# Can you see the available options in the code? We have to create a 
# drop-down menu for the user to choose
workflow = 'FBMN'
metric = 'euclidean'
gnps_result = Proteosafe(taskid, workflow)
gnps_result.get_gnps()

In [10]:
gnps_result.meta.head()

,filename,ATTRIBUTE_Sample_Number,ATTRIBUTE_Order_Injection_2965_3788,ATTRIBUTE_Plot,ATTRIBUTE_Forest_Region,ATTRIBUTE_Pertubation,ATTRIBUTE_Super_Order_APGIV_Clade,ATTRIBUTE_Order_APGIV_Order,ATTRIBUTE_Family,ATTRIBUTE_Genus,...,ATTRIBUTE_Order_APGIII,ATTRIBUTE_CS,ATTRIBUTE_AB,ATTRIBUTE_LIG,ATTRIBUTE_AFE,ATTRIBUTE_CMSF,ATTRIBUTE_Asat,ATTRIBUTE_C,ATTRIBUTE_N,ATTRIBUTE_C/N
0,10_3uL_30_05_1-33_01_3004.mzXML,10,3004,T,Secondary,Clearcut,Monocots,Arecales,Arecaceae,Euterpe,...,0.105,0.135,0.016,0.387,0.120,456.674,32.262,14.155,NaN,NaN
1,11_3uL_01_06_1-42_01_3131.mzXML,11,3131,T,Secondary,Clearcut,Monocots,Arecales,Arecaceae,Euterpe,...,0.105,0.135,0.016,0.387,0.120,456.674,32.262,14.155,NaN,NaN
2,12_3uL_30_05_1-68_01_3052.mzXML,12,3052,T,Secondary,Clearcut,Monocots,Arecales,Arecaceae,Euterpe,...,0.105,0.135,0.016,0.387,0.120,456.674,32.262,14.155,NaN,NaN
3,78_3uL_03_07_1-66_01_3757.mzXML,78,3757,K,Primary,Preserved,Monocots,Arecales,Arecaceae,Euterpe,...,0.116,0.211,0.010,0.347,0.064,484.183,23.933,20.231,NaN,NaN
4,79_3uL_03_07_1-17_01_3699.mzXML,79,3699,K,Primary,Preserved,Monocots,Arecales,Arecaceae,Euterpe,...,0.116,0.211,0.010,0.347,0.064,484.183,23.933,20.231,NaN,NaN

In [11]:
gnps_result.feat.head()

,row ID,row m/z,row retention time,12_3uL_30_05_1-68_01_3052.mzXML Peak area,78_3uL_03_07_1-66_01_3757.mzXML Peak area,11_3uL_01_06_1-42_01_3131.mzXML Peak area,10_3uL_30_05_1-33_01_3004.mzXML Peak area,80_3uL_30_05_1-58_01_3033.mzXML Peak area,153_3uL_01_06_1-23_01_3111.mzXML Peak area,152_3uL_01_06_1-87_01_3074.mzXML Peak area,79_3uL_03_07_1-17_01_3699.mzXML Peak area,224_3uL_03_07_1-81_01_3774.mzXML Peak area,154_3uL_01_06_1-37_01_3125.mzXML Peak area,225_3uL_03_07_1-92_01_3787.mzXML Peak area,226_3uL_03_07_1-6_01_3686.mzXML Peak area,Unnamed: 15
0,5,353.265401,35.119569,1.099282e+06,1631616.110,1.281668e+06,860049.175,1254956.950,1.010253e+06,900838.985,1.441528e+06,1.391126e+06,1.317142e+06,1.292446e+06,2443.4200,NaN
1,7,381.296298,37.262528,9.998174e+05,1445426.520,1.249140e+06,915588.990,1234167.890,9.921647e+05,800190.520,1.270731e+06,1.384528e+06,1.256917e+06,1.198393e+06,303.0000,NaN
2,8,581.148154,7.884651,1.348523e+06,1536205.639,5.228738e+06,1779064.237,127515.698,1.108239e+05,36034.871,2.423437e+04,1.746068e+06,1.812014e+05,3.515917e+04,338.3965,NaN
3,10,609.268397,35.247439,5.505347e+05,1259964.695,1.099087e+06,1900706.545,525107.070,4.631662e+05,325802.580,3.167505e+05,3.375690e+06,6.051916e+05,1.972567e+06,0.0000,NaN
4,13,305.156498,49.782424,6.643086e+05,299720.325,8.127709e+05,559341.440,714114.810,9.085950e+05,683273.360,4.172964e+05,3.073419e+05,7.009724e+05,4.861288e+05,0.0000,NaN

In [12]:
sample_metadata = gnps_result.meta
df = gnps_result.feat

sample_metadata.rename(index=str, columns={"filename": "#SampleID"},
                           inplace=True)
sample_metadata.columns = sample_metadata.columns.str.replace('\s', '_')

sample_metadata.index = sample_metadata['#SampleID']
sample_metadata.drop(['#SampleID'], axis=1, inplace=True)
qsample_metadata = qiime2.metadata.Metadata(sample_metadata)

df2 = df[df.columns[df.columns.str.contains(' Peak area')]]
df2.columns = [re.sub('(.+\.mzX?ML) .+', '\\1', a) for a in df2.columns]
df2.index = df['row ID'].astype(str)
df2 = df2.T

/tmp/ipykernel_93/4162826805.py:6: FutureWarning: The default value of regex will change from True to False in a future version.
  sample_metadata.columns = sample_metadata.columns.str.replace('\s', '_')

In [13]:
df2.head()

row ID,5,7,8,10,13,15,16,17,19,20,...,3214,3236,3249,3258,3276,3280,3309,3312,3318,3357
12_3uL_30_05_1-68_01_3052.mzXML,1099282.475,999817.425,1.348523e+06,550534.675,664308.600,872762.290,394166.740,679873.427,380556.605,8.229792e+05,...,307.53,137.700,886.780,230.000,0.0,84.15,211.630,253.98,176.13,138.72
78_3uL_03_07_1-66_01_3757.mzXML,1631616.110,1445426.520,1.536206e+06,1259964.695,299720.325,1102765.640,539348.905,606.372,839610.910,1.195869e+06,...,242.25,419.195,1802.900,0.000,0.0,110.67,1571.560,233.07,0.00,252.45
11_3uL_01_06_1-42_01_3131.mzXML,1281667.895,1249140.445,5.228738e+06,1099087.450,812770.880,900354.130,568145.865,449986.256,890581.265,9.003798e+05,...,685.80,86.840,435.375,198.940,0.0,71.40,651.780,358.02,328.90,260.10
10_3uL_30_05_1-33_01_3004.mzXML,860049.175,915588.990,1.779064e+06,1900706.545,559341.440,652475.155,841555.890,359513.092,1468203.685,5.970800e+02,...,448.80,408.880,2410.925,177.030,0.0,100.37,390.660,292.23,151.47,493.29
80_3uL_30_05_1-58_01_3033.mzXML,1254956.950,1234167.890,1.275157e+05,525107.070,714114.810,919774.190,252188.315,146.088,368269.425,2.025829e+04,...,374.85,110.670,131.070,135.355,86.7,98.94,43.645,422.56,655.20,171.00

In [24]:
# current version
# pqn
#        if self.normType == 'PQN':
#            medians = df.median(axis=1)
#            normalized_df = df.div(medians, axis=0)
#            normalized_df *= medians.median()
#            return normalized_df

In [14]:
# 12 samples 'n' samples on the paper
# 486 variables 'd' variables
df2.shape

(12, 486)

In [15]:
medians = df2.median(axis=1)
medians.shape

(12,)

In [16]:
# Example 3 samples, 4 variables
# Validate against other implementation
# https://rdrr.io/github/ricoderks/Rcpm/src/R/pqn.R
temp = pd.DataFrame([[2.0438199, -0.4881113,  0.7856725, -0.8118500],
                     [-0.7760712, -0.7189763, -0.9654193,  0.8786014],
                     [1.1694329, -0.4759941, -1.1107615, -2.1956906]])

temp.median()

0    1.169433
1   -0.488111
2   -0.965419
3   -0.811850
dtype: float64

In [17]:
temp.div(temp.median(), axis=1)

          0         1         2         3
0  1.747702  1.000000 -0.813815  1.000000
1 -0.663630  1.472976  1.000000 -1.082221
2  1.000000  0.975175  1.150548  2.704552

In [18]:
median_temp = temp.div(temp.median(), axis=1)
median_temp.median(axis=1)

0    1.000000
1    0.168185
2    1.075274
dtype: float64

In [19]:
temp.div(median_temp.median(axis=1), axis=0)

          0         1         2         3
0  2.043820 -0.488111  0.785672 -0.811850
1 -4.614395 -4.274918 -5.740229  5.224024
2  1.087567 -0.442672 -1.033003 -2.041982

In [20]:
temp[0]/median_temp.median(axis=1)

0    2.043820
1   -4.614395
2    1.087567
dtype: float64

In [21]:
df2.median().shape

(486,)

In [33]:
#fixed PQN
ref_spec = df2.median(axis=0)
ref_spec

row ID
5       1.268312e+06
7       1.216280e+06
8       1.543585e+05
10      5.778631e+05
13      6.118250e+05
            ...
3280    1.055200e+02
3309    4.145000e+02
3312    3.902900e+02
3318    1.638000e+02
3357    3.520275e+02
Length: 486, dtype: float64

In [30]:
quotion = df2.T.div(ref_spec.values, axis=0)
quotion

,12_3uL_30_05_1-68_01_3052.mzXML,78_3uL_03_07_1-66_01_3757.mzXML,11_3uL_01_06_1-42_01_3131.mzXML,10_3uL_30_05_1-33_01_3004.mzXML,80_3uL_30_05_1-58_01_3033.mzXML,153_3uL_01_06_1-23_01_3111.mzXML,152_3uL_01_06_1-87_01_3074.mzXML,79_3uL_03_07_1-17_01_3699.mzXML,224_3uL_03_07_1-81_01_3774.mzXML,154_3uL_01_06_1-37_01_3125.mzXML,225_3uL_03_07_1-92_01_3787.mzXML,226_3uL_03_07_1-6_01_3686.mzXML
row ID,,,,,,,,,,,,
5,0.866728,1.286447,1.010530,0.678105,0.989470,0.796534,0.710266,1.136571,1.096832,1.038500,1.019028,0.001927
7,0.822029,1.188399,1.027017,0.752778,1.014707,0.815737,0.657900,1.044769,1.138330,1.033410,0.985293,0.000249
8,8.736302,9.952191,33.873983,11.525532,0.826101,0.717964,0.233449,0.157001,11.311768,1.173899,0.227776,0.002192
10,0.952708,2.180386,1.901986,3.289198,0.908705,0.801515,0.563806,0.548141,5.841677,1.047292,3.413554,0.000000
13,1.085782,0.489879,1.328437,0.914218,1.167188,1.485057,1.116779,0.682052,0.502336,1.145707,0.794555,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
3280,0.797479,1.048806,0.676649,0.951194,0.937642,3.770470,1.290466,2.237775,0.855478,1.391964,0.531653,278.971806
3309,0.510567,3.791460,1.572449,0.942485,0.105296,1.057515,0.743776,2.139759,11.505899,0.374041,0.567214,69.771146
3312,0.650747,0.597171,0.917318,0.748751,1.082682,1.110713,1.698737,0.000000,2.772938,1.907812,0.734377,65.806772
3318,1.075275,0.000000,2.007937,0.924725,4.000000,0.675641,1.105311,0.000000,1.383150,0.000000,0.000000,155.040110
3357,0.394060,0.717131,0.738863,1.401283,0.485758,1.068453,1.588313,0.628758,1.279247,0.931547,1.176385,79.823551

In [31]:
factor = quotion.median(axis=1)
factor

row ID
5       1.0
7       1.0
8       1.0
10      1.0
13      1.0
       ...
3280    1.0
3309    1.0
3312    1.0
3318    1.0
3357    1.0
Length: 486, dtype: float64

In [32]:
normalizedDf = df2.div(factor.values, axis=1)
normalizedDf

row ID,5,7,8,10,13,15,16,17,19,20,...,3214,3236,3249,3258,3276,3280,3309,3312,3318,3357
12_3uL_30_05_1-68_01_3052.mzXML,1099282.475,999817.425,1.348523e+06,550534.675,664308.600,872762.290,394166.740,679873.4270,380556.605,8.229792e+05,...,307.530,137.700,886.780,230.000,0.0,84.150,211.630,253.980,176.13,138.720
78_3uL_03_07_1-66_01_3757.mzXML,1631616.110,1445426.520,1.536206e+06,1259964.695,299720.325,1102765.640,539348.905,606.3720,839610.910,1.195869e+06,...,242.250,419.195,1802.900,0.000,0.0,110.670,1571.560,233.070,0.00,252.450
11_3uL_01_06_1-42_01_3131.mzXML,1281667.895,1249140.445,5.228738e+06,1099087.450,812770.880,900354.130,568145.865,449986.2560,890581.265,9.003798e+05,...,685.800,86.840,435.375,198.940,0.0,71.400,651.780,358.020,328.90,260.100
10_3uL_30_05_1-33_01_3004.mzXML,860049.175,915588.990,1.779064e+06,1900706.545,559341.440,652475.155,841555.890,359513.0920,1468203.685,5.970800e+02,...,448.800,408.880,2410.925,177.030,0.0,100.370,390.660,292.230,151.47,493.290
80_3uL_30_05_1-58_01_3033.mzXML,1254956.950,1234167.890,1.275157e+05,525107.070,714114.810,919774.190,252188.315,146.0880,368269.425,2.025829e+04,...,374.850,110.670,131.070,135.355,0.0,98.940,43.645,422.560,655.20,171.000
153_3uL_01_06_1-23_01_3111.mzXML,1010253.345,992164.710,1.108239e+05,463166.165,908594.980,220229.915,225709.800,174783.8685,398034.380,8.658633e+04,...,339.660,0.000,309.925,68.850,0.0,397.860,438.340,433.500,110.67,376.125
152_3uL_01_06_1-87_01_3074.mzXML,900838.985,800190.520,3.603487e+04,325802.580,683273.360,229846.810,139386.755,404869.6455,189757.750,4.746639e+04,...,193.290,183.425,355.520,138.040,0.0,136.170,308.295,663.000,181.05,559.130
79_3uL_03_07_1-17_01_3699.mzXML,1441527.725,1270731.465,2.423437e+04,316750.470,417296.370,435106.770,100755.380,539159.1750,169125.900,2.965351e+05,...,225.930,58.140,331.660,0.000,0.0,236.130,886.930,0.000,0.00,221.340
224_3uL_03_07_1-81_01_3774.mzXML,1391125.840,1384528.470,1.746068e+06,3375689.690,307341.950,1394908.370,2403359.115,2995.4795,1667862.165,6.669988e+05,...,462.500,1630.140,643.800,0.000,0.0,90.270,4769.195,1082.250,226.56,450.330
154_3uL_01_06_1-37_01_3125.mzXML,1317142.430,1256916.555,1.812014e+05,605191.590,700972.355,255182.755,209288.390,46968.5845,481537.125,6.759795e+03,...,171.870,43.350,232.050,120.870,0.0,146.880,155.040,744.600,0.00,327.930
225_3uL_03_07_1-92_01_3787.mzXML,1292446.440,1198392.935,3.515917e+04,1972566.810,486128.760,1309614.530,802718.510,328.4400,1324835.435,1.239769e+05,...,542.640,468.930,1354.960,0.000,0.0,56.100,235.110,286.620,0.00,414.120
226_3uL_03_07_1-6_01_3686.mzXML,2443.420,303.000,3.383965e+02,0.000,0.000,840.825,369.460,278.9700,0.000,0.000000e+00,...,43009.015,54107.025,26975.890,31517.930,0.0,29437.105,28920.140,25683.725,25395.57,28100.085

In [35]:
df2.shape

(12, 486)

In [22]:
# TIC
normalized_df = df2.apply(lambda a: a/sum(a), axis=1)

normalized_df.head()

row ID,5,7,8,10,13,15,16,17,19,20,...,3214,3236,3249,3258,3276,3280,3309,3312,3318,3357
12_3uL_30_05_1-68_01_3052.mzXML,0.032602,0.029652,0.039994,0.016328,0.019702,0.025884,0.011690,0.020164,0.011286,0.024408,...,0.000009,0.000004,0.000026,0.000007,0.000000,0.000002,0.000006,0.000008,0.000005,0.000004
78_3uL_03_07_1-66_01_3757.mzXML,0.031309,0.027736,0.029478,0.024177,0.005751,0.021161,0.010349,0.000012,0.016111,0.022947,...,0.000005,0.000008,0.000035,0.000000,0.000000,0.000002,0.000030,0.000004,0.000000,0.000005
11_3uL_01_06_1-42_01_3131.mzXML,0.025865,0.025209,0.105520,0.022180,0.016402,0.018170,0.011466,0.009081,0.017973,0.018170,...,0.000014,0.000002,0.000009,0.000004,0.000000,0.000001,0.000013,0.000007,0.000007,0.000005
10_3uL_30_05_1-33_01_3004.mzXML,0.020314,0.021625,0.042020,0.044893,0.013211,0.015411,0.019877,0.008491,0.034678,0.000014,...,0.000011,0.000010,0.000057,0.000004,0.000000,0.000002,0.000009,0.000007,0.000004,0.000012
80_3uL_30_05_1-58_01_3033.mzXML,0.049144,0.048330,0.004994,0.020563,0.027965,0.036018,0.009876,0.000006,0.014421,0.000793,...,0.000015,0.000004,0.000005,0.000005,0.000003,0.000004,0.000002,0.000017,0.000026,0.000007

In [23]:
# All samples sum to 1
# sanity check is ok
normalized_df.sum(axis=1)

12_3uL_30_05_1-68_01_3052.mzXML     1.0
78_3uL_03_07_1-66_01_3757.mzXML     1.0
11_3uL_01_06_1-42_01_3131.mzXML     1.0
10_3uL_30_05_1-33_01_3004.mzXML     1.0
80_3uL_30_05_1-58_01_3033.mzXML     1.0
153_3uL_01_06_1-23_01_3111.mzXML    1.0
152_3uL_01_06_1-87_01_3074.mzXML    1.0
79_3uL_03_07_1-17_01_3699.mzXML     1.0
224_3uL_03_07_1-81_01_3774.mzXML    1.0
154_3uL_01_06_1-37_01_3125.mzXML    1.0
225_3uL_03_07_1-92_01_3787.mzXML    1.0
226_3uL_03_07_1-6_01_3686.mzXML     1.0
dtype: float64

In [24]:
# autoscaling
scaled_df = (df2 - df2.mean()) / (df2.std())

scaled_df.head()

row ID,5,7,8,10,13,15,16,17,19,20,...,3214,3236,3249,3258,3276,3280,3309,3312,3318,3357
12_3uL_30_05_1-68_01_3052.mzXML,-0.058108,-0.161682,0.220540,-0.499475,0.460604,0.393378,-0.225378,1.827118,-0.545206,1.107543,...,-0.293174,-0.300454,-0.277118,-0.274021,-0.289398,-0.295142,-0.366368,-0.313085,-0.287240,-0.312889
78_3uL_03_07_1-66_01_3757.mzXML,1.213274,0.991748,0.343840,0.235148,-0.960693,0.891587,-0.000620,-0.881245,0.286357,1.975880,...,-0.298476,-0.282331,-0.156367,-0.299377,-0.289398,-0.292006,-0.200487,-0.315952,-0.311415,-0.298702
11_3uL_01_06_1-42_01_3131.mzXML,0.377487,0.483674,2.769691,0.068558,1.039364,0.453145,0.043961,0.910515,0.378688,1.287783,...,-0.262450,-0.303729,-0.336617,-0.277446,-0.289398,-0.296649,-0.312680,-0.298823,-0.266270,-0.297748
10_3uL_30_05_1-33_01_3004.mzXML,-0.629473,-0.379702,0.503389,0.898644,0.051404,-0.083784,0.467230,0.549782,1.425033,-0.807513,...,-0.281700,-0.282995,-0.076226,-0.279861,-0.289398,-0.293224,-0.344531,-0.307842,-0.290624,-0.268660
80_3uL_30_05_1-58_01_3033.mzXML,0.313692,0.444919,-0.581614,-0.525806,0.654767,0.495210,-0.445177,-0.883081,-0.567464,-0.761728,...,-0.287706,-0.302194,-0.376726,-0.284455,-0.281442,-0.293393,-0.386859,-0.289975,-0.221482,-0.308862

In [25]:
# mean scaled ~ 0 for all variables
# check ok
scaled_df.mean()

row ID
5       2.220446e-16
7       2.590520e-16
8       1.850372e-17
10      1.665335e-16
13      2.960595e-16
            ...
3280   -3.700743e-17
3309   -7.401487e-17
3312   -3.700743e-17
3318    0.000000e+00
3357    3.700743e-17
Length: 486, dtype: float64

In [26]:
# std ~ 1 for all variables
# check ok
scaled_df.std()

row ID
5       1.0
7       1.0
8       1.0
10      1.0
13      1.0
       ...
3280    1.0
3309    1.0
3312    1.0
3318    1.0
3357    1.0
Length: 486, dtype: float64